export const TASK_GET_STARTED = "TASK_GET_STARTED"; 
export const TASK_GET_DONE = "TASK_GET_DONE";
export const TASK_CREATE_STARTED = "TASK_CREATE_STARTED";
export const TASK_CREATE_DONE = "TASK_CREATE_DONE";


export const SETTINGS_UPDATE_TASK_SORTING = "SETTINGS_UPDATE_TASK_SORTING";
export const SETTINGS_UPDATE_TASK_VISIBILITY_FILTER = "SETTINGS_UPDATE_TASK_VISIBILITY_FILTER";


// export const TASK_EDIT_REQUEST = "TASK_EDIT_REQUEST";
// export const TASK_EDIT_RECEIVED = "TASK_EDIT_RECEIVED";

// export const TASK_EDIT_STATE_RESET = "TASK_EDIT_STATE_RESET";
// export const TASK_EDIT_SUCCESS = "TASK_EDIT_SUCCESS";
// export const TASK_EDIT_ERROR = "TASK_EDIT_ERROR";
// export const TASK_ACTIVE = "TASK_ACTIVE";
// export const TASK_ACTIVE_SUCCESS = "TASK_ACTIVE_SUCCESS";
// export const TASK_ACTIVE_ERROR = "TASK_ACTIVE_ERROR";
// export const TASK_COMPLETE = "TASK_COMPLETE";
// export const TASK_COMPLETE_SUCCESS = "TASK_COMPLETE_SUCCESS";
// export const TASK_COMPLETE_ERROR = "TASK_COMPLETE_ERROR";
// export const TASK_DELETE = "TASK_DELETE";
// export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS";
// export const TASK_DELETE_ERROR = "TASK_DELETE_ERROR";
// export const TASK_CLEAR_COMPLETED = "TASK_CLEAR_COMPLETED";
// export const TASK_CLEAR_COMPLETED_SUCCESS = "TASK_DELETE_SUCCESS";
// export const TASK_CLEAR_COMPLETED_ERROR = "TASK_DELETE_ERROR";