export const TASK_GET_STARTED = "TASK_GET_STARTED"; 
export const TASK_GET_DONE = "TASK_GET_DONE";
export const TASK_CREATE_STARTED = "TASK_CREATE_STARTED";
export const TASK_CREATE_DONE = "TASK_CREATE_DONE";
export const TASK_ACTIVE = "TASK_ACTIVE";
export const TASK_COMPLETE = "TASK_COMPLETE";
export const TASK_DELETE = "TASK_DELETE";
export const TASK_UPDATE_STARTED = "TASK_UPDATE_STARTED";
export const TASK_UPDATE_DONE = "TASK_UPDATE_DONE";

export const SETTINGS_UPDATE_TASK_SORT_BY = "SETTINGS_UPDATE_TASK_SORT_BY";
export const SETTINGS_UPDATE_TASK_SORT_BY_ORDER = "SETTINGS_UPDATE_TASK_SORT_BY_ORDER";
export const SETTINGS_UPDATE_TASK_VISIBILITY_FILTER = "SETTINGS_UPDATE_TASK_VISIBILITY_FILTER";