export const TASK_GET_REQUEST = "TASK_GET_REQUEST"; 
export const TASK_GET_RECEIVED = "TASK_GET_RECEIVED"; 

// export const TASK_CREATE_REQUEST = "TASK_CREATE_REQUEST";
// export const TASK_CREATE_RECEIVED = "TASK_CREATE_RECEIVED";

// export const TASK_EDIT_REQUEST = "TASK_EDIT_REQUEST";
// export const TASK_EDIT_RECEIVED = "TASK_EDIT_RECEIVED";

// export const TASK_EDIT_STATE_RESET = "TASK_EDIT_STATE_RESET";
// export const TASK_EDIT_SUCCESS = "TASK_EDIT_SUCCESS";
// export const TASK_EDIT_ERROR = "TASK_EDIT_ERROR";
// export const TASK_ACTIVE = "TASK_ACTIVE";
// export const TASK_ACTIVE_SUCCESS = "TASK_ACTIVE_SUCCESS";
// export const TASK_ACTIVE_ERROR = "TASK_ACTIVE_ERROR";
// export const TASK_COMPLETE = "TASK_COMPLETE";
// export const TASK_COMPLETE_SUCCESS = "TASK_COMPLETE_SUCCESS";
// export const TASK_COMPLETE_ERROR = "TASK_COMPLETE_ERROR";
// export const TASK_DELETE = "TASK_DELETE";
// export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS";
// export const TASK_DELETE_ERROR = "TASK_DELETE_ERROR";
// export const TASK_CLEAR_COMPLETED = "TASK_CLEAR_COMPLETED";
// export const TASK_CLEAR_COMPLETED_SUCCESS = "TASK_DELETE_SUCCESS";
// export const TASK_CLEAR_COMPLETED_ERROR = "TASK_DELETE_ERROR";